### ISSUE TITLE
Rectángulo negro

### ISSUE THREAD

**Issue by Aimonius** [danielredondo/30diasdegraficos#1]
Hola Daniel. Estoy intentando reproducir tu código para el Mapa de Granada capital con calles y ríos y me he encontrado un problema:me funciona perfectamente para Granada, pero si la sustituyo por cualquier otra ciudad, solo consigo un rectángulo totalmente negro, aunque cambio todas las ocurrencias de Granada por las de la ciudad que elijo. 

La consola no me lanza ningún error, así que no me hago una idea de donde puede estar el fallo.

**Comment by danielredondo** [comment]
Buenas Jesús. Es porque el mapa muestra sólo las coordenadas que le indicas, y el script está preparado para Granada. Por eso hago getbb (boundary box) al principio del código, y especifico las coordenadas en el coord_sf al final del gráfico. Prueba a cambiar esto y dime si te sigue sin salir, cierro el issue.

**Comment by Aimonius** [comment]
Eso era. Muchas gracias Daniel :)
